=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

def fib(n)
	return 0 if n==0
	return 1 if (n==1 || n==2)
	fib(n-1)+fib(n-2)
end

fib_number = 0
current_fib = fib(0)
sum = 0

while current_fib < 4000000
	current_fib = fib(fib_number)
	sum+= current_fib if current_fib % 2 == 0
	fib_number+=1
end

puts "#{fib_number}, #{current_fib}, #{sum}"



